In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
from IPython.display import Image
from sklearn.metrics import accuracy_score

random.seed(0)
np.random.seed(0)

In [2]:
training = pd.read_csv('optdigits.tra',names=np.arange(64))
training

0   1   2   3   4   5   6   7   8   9   ...  54  55  56  57  58  59  60  \
0    1   6  15  12   1   0   0   0   7  16  ...   0   0   0   6  14   7   1   
0    0  10  16   6   0   0   0   0   7  16  ...   0   0   0  10  16  15   3   
0    0   8  15  16  13   0   0   0   1  11  ...   0   0   0   9  14   0   0   
0    0   0   3  11  16   0   0   0   0   5  ...   0   0   0   0   1  15   2   
0    0   5  14   4   0   0   0   0   0  13  ...   0   0   0   4  12  14   7   
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
0    0   5  13  11   2   0   0   0   2  15  ...   0   0   0   8  13  15  10   
0    0   0   1  12   1   0   0   0   0   0  ...   0   0   0   0   4   9   0   
0    0   3  15   0   0   0   0   0   0  11  ...   0   0   0   4  14  16   9   
0    0   6  16   2   0   0   0   0   0  15  ...   0   0   0   5  16  16  16   
0    0   2  15  16  13   1   0   0   0   3  ...   0   0   0   4  14   1   0   

    61  62  63  
0    0   0   0  
0    0   0   0  
0    0   0   7  
0    0   0   4  
0    0   0   6  
..  ..  ..  ..  
0    1   0   9  
0    0   0   4  
0    0   0   6  
0    5   0   6  
0    0   0   7  

[3823 rows x 64 columns]

In [3]:
testing = pd.read_csv('optdigits.tes',names=np.arange(64))
testing

0   1   2   3   4   5   6   7   8   9   ...  54  55  56  57  58  59  60  \
0    0   5  13   9   1   0   0   0   0  13  ...   0   0   0   6  13  10   0   
0    0   0  12  13   5   0   0   0   0   0  ...   0   0   0   0  11  16  10   
0    0   0   4  15  12   0   0   0   0   3  ...   0   0   0   0   3  11  16   
0    0   7  15  13   1   0   0   0   8  13  ...   0   0   0   7  13  13   9   
0    0   0   1  11   0   0   0   0   0   0  ...   0   0   0   0   2  16   4   
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
0    0   4  10  13   6   0   0   0   1  16  ...   0   0   0   2  14  15   9   
0    0   6  16  13  11   1   0   0   0  16  ...   0   0   0   6  16  14   6   
0    0   1  11  15   1   0   0   0   0  13  ...   0   0   0   2   9  13   6   
0    0   2  10   7   0   0   0   0   0  14  ...   0   0   0   5  12  16  12   
0    0  10  14   8   1   0   0   0   2  16  ...   0   0   1   8  12  14  12   

    61  62  63  
0    0   0   0  
0    0   0   1  
0    9   0   2  
0    0   0   3  
0    0   0   4  
..  ..  ..  ..  
0    0   0   9  
0    0   0   0  
0    0   0   8  
0    0   0   9  
0    1   0   8  

[1797 rows x 64 columns]

In [4]:
X = training.drop(63,axis=1)
X

0   1   2   3   4   5   6   7   8   9   ...  53  54  55  56  57  58  59  \
0    1   6  15  12   1   0   0   0   7  16  ...   0   0   0   0   6  14   7   
0    0  10  16   6   0   0   0   0   7  16  ...   3   0   0   0  10  16  15   
0    0   8  15  16  13   0   0   0   1  11  ...   0   0   0   0   9  14   0   
0    0   0   3  11  16   0   0   0   0   5  ...   0   0   0   0   0   1  15   
0    0   5  14   4   0   0   0   0   0  13  ...  12   0   0   0   4  12  14   
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
0    0   5  13  11   2   0   0   0   2  15  ...  10   0   0   0   8  13  15   
0    0   0   1  12   1   0   0   0   0   0  ...   0   0   0   0   0   4   9   
0    0   3  15   0   0   0   0   0   0  11  ...   4   0   0   0   4  14  16   
0    0   6  16   2   0   0   0   0   0  15  ...  15   0   0   0   5  16  16   
0    0   2  15  16  13   1   0   0   0   3  ...   0   0   0   0   4  14   1   

    60  61  62  
0    1   0   0  
0    3   0   0  
0    0   0   0  
0    2   0   0  
0    7   0   0  
..  ..  ..  ..  
0   10   1   0  
0    0   0   0  
0    9   0   0  
0   16   5   0  
0    0   0   0  

[3823 rows x 63 columns]

In [5]:
Y = training[[63]]
Y

63
0    0
0    0
0    7
0    4
0    6
..  ..
0    9
0    4
0    6
0    6
0    7

[3823 rows x 1 columns]

<b>Formulas to use:</b>

In [6]:
Image(url= "Logistic_Regression-1.png")

In [7]:
Image(url= "Logistic Regression-2.png")

In [8]:
Image(url= "Logistic_Regression-3.png")

In [9]:
Image(url= "Logistic_Regression-4.png")

<b>First making a model for binary classification:</b>

In [10]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [11]:
def htheta(theta,x):
    return sigmoid(np.dot(x,theta))

In [12]:
def cal_cost(x,y,theta):
    h = htheta(theta,x)
    m = len(x)
    return (-1/m * (np.sum(y*np.log(h)+(1-y)*np.log(1-h))))

In [22]:
def gd(alpha,x,y,iterations):
    m = len(x)
    ones =np.ones((m,1)) 
    x = np.concatenate((ones, x), axis=1) 
    n = x.shape[1]
    theta = np.ones(x.shape[1])
    h = htheta(theta,x)
    cost = np.ones(iterations)
    for i in range(0,iterations):
        for j in range(0,n):
            theta[j] = theta[j] - ((alpha/m)*np.sum((h-y)*x[:,j]))   
    return theta

In [23]:
def log_reg(x,y,alpha,iterations):
    theta = gd(alpha,x,y,iterations)
    return theta

In [24]:
fake_Y = np.concatenate((np.ones(3000),np.zeros(823)),axis=0)
fake_Y = fake_Y.reshape(len(fake_Y),1)
fake_Y.shape

(3823, 1)

In [26]:
theta = log_reg(np.array(X),fake_Y,0.0002,10)
theta

array([ -0.646     ,   0.50400419,  -8.02307664, -18.43253047,
       -17.84913262,  -8.06182631,  -1.2836474 ,   0.76577975,
         0.99655558,  -2.22698666, -16.41022809, -18.28355951,
       -16.48858854, -12.65452367,  -2.62137222,   0.74984933,
         0.99181951,  -3.27279728, -14.76982527, -10.0858509 ,
       -10.82898352, -12.24765211,  -2.36777714,   0.91905624,
         0.99827779,  -2.84439812, -14.20752446, -14.03401203,
       -14.92224065, -11.95014073,  -2.85214805,   0.99483338,
         0.99784724,  -2.36261052, -11.6074214 , -14.20580225,
       -16.03220351, -14.14337222,  -3.79419566,   1.        ,
         0.95479205,  -1.31378603,  -9.62774366, -10.83027518,
       -12.03883442, -13.27882396,  -4.7780068 ,   0.96727805,
         0.97072247,  -0.34978028, -11.95229349, -15.27184881,
       -15.07293382, -14.28028773,  -5.16248967,   0.75587706,
         0.99956945,   0.53414282,  -8.63876589, -18.65813968,
       -17.86506304, -10.02901805,  -2.46594298,   0.66

In [ ]:
X_test = testing.drop(63,axis=1)
X_test = np.array(X_test)
X_test

In [370]:
X_test = (X_test-X_test.meandd())/X_test.std()

<b>For multiclass classification(One vs all method):</b>

In [27]:
#Create different output classes for each of the output
classes = Y[63].unique()
classes

array([0, 7, 4, 6, 2, 5, 8, 1, 9, 3], dtype=int64)

In [28]:
Y_new = np.zeros(shape=(len(X),len(classes)))
Y_new = pd.DataFrame(Y_new,columns=classes)       
Y_new

0    7    4    6    2    5    8    1    9    3
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
3818  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3819  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3820  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3821  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3822  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[3823 rows x 10 columns]

In [29]:
for i in range(0, len(Y)):
    val = Y[63].iloc[i]
    Y_new[val].iloc[i] = 1
        
Y_new

0    7    4    6    2    5    8    1    9    3
0     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2     0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3     0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
3818  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
3819  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3820  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
3821  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
3822  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[3823 rows x 10 columns]

In [31]:
theta_all_classes = {}
for i in range(0,len(classes)):
    t = log_reg(np.array(X),np.array(Y_new[classes[i]]).reshape(len(Y),),0.0002,10)
    theta_all_classes[classes[i]] = t
theta_all_classes

{0: array([0.9981967 , 0.99940309, 0.98993199, 0.97898038, 0.9792498 ,
        0.98950772, 0.99723673, 0.99971541, 0.99999581, 0.99630866,
        0.98139733, 0.97914674, 0.98116505, 0.98551713, 0.99574523,
        0.99969605, 0.99999006, 0.99557049, 0.98366571, 0.98745279,
        0.98621658, 0.98640753, 0.99656239, 0.99990165, 0.99999791,
        0.99635731, 0.98403087, 0.98206016, 0.98071828, 0.98607743,
        0.99662359, 0.99999372, 0.99999738, 0.99698143, 0.9870238 ,
        0.98170965, 0.97934031, 0.98330526, 0.99562804, 1.        ,
        0.99994507, 0.99784096, 0.98974784, 0.98597855, 0.98444311,
        0.98488988, 0.99424902, 0.99996024, 0.99996443, 0.99851007,
        0.98684279, 0.98230813, 0.98256291, 0.98408632, 0.99304211,
        0.99970337, 0.99999948, 0.99943761, 0.9891865 , 0.97878002,
        0.97969867, 0.98769291, 0.99582841, 0.99959561]),
 7: array([0.99820246, 0.99947685, 0.99045095, 0.97909129, 0.98001569,
        0.99148627, 0.99848862, 0.99991368, 0.999995

In [32]:
pd.DataFrame(theta_all_classes).iloc[:,0]

0     0.998197
1     0.999403
2     0.989932
3     0.978980
4     0.979250
        ...   
59    0.978780
60    0.979699
61    0.987693
62    0.995828
63    0.999596
Name: 0, Length: 64, dtype: float64

In [43]:
predict_all = []
for i in range(0, len(classes)):
    theta_i = pd.DataFrame(theta_all_classes)
    h = htheta(theta_i.iloc[:,i], X)
    predict_all.append(h)
predict_all=pd.DataFrame(predict_all)

In [52]:
htheta(theta_all_classes[0],X)

array([1., 1., 1., ..., 1., 1., 1.])

In [54]:
np.dot(X,theta_all_classes[0])

array([238.69297149, 294.39620978, 242.31375621, ..., 250.03898509,
       275.43135757, 196.21581219])